name: E2E

on: [push]

jobs:
  end-to-end-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - sfra-version: "v5.3.0"
            sfcc-hostname: ${{ secrets.SFCC_HOSTNAME_SFRA5 }}
            code-version: ${{ secrets.SFCC_CODE_VERSION_SFRA5 }}
          - node-version: "v6.0.0"
            sfcc-hostname: ${{ secrets.SFCC_HOSTNAME_SFRA6 }}
            code-version: ${{ secrets.SFCC_CODE_VERSION_SFRA6 }}
    steps:
      - name: Checkout SFRA code
        uses: actions/checkout@v2
        with:
          repository: SalesforceCommerceCloud/storefront-reference-architecture
          ref: v5.3.0
          ssh-key: ${{ secrets.SERVICE_ACCOUNT_SSH_KEY }}
          path: storefront-reference-architecture
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: adyen-salesforce-commerce-cloud
      - name: npm install storefront-reference-architecture
        working-directory: storefront-reference-architecture
        run: npm install
      - name: npm install adyen-salesforce-commerce-cloud
        working-directory: adyen-salesforce-commerce-cloud
        run: npm install
      - name: create dw.json file
        working-directory: adyen-salesforce-commerce-cloud
        run: |
          echo '{
            "username": "${{ secrets.SFCC_USERNAME }}",
            "password": "${{ secrets.SFCC_PASSWORD }}",
            "hostname": "${{ matrix.sfcc-hostname }}",
            "code-version": "${{ matrix.code-version }}"
          }' >> dw.json
      - name: push cartridge code
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run build
      - name: run e2e tests
        working-directory: adyen-salesforce-commerce-cloud
        run: npm run test:e2e
        env:
          SANDBOX_HTTP_AUTH_USERNAME: ${{ secrets.SANDBOX_HTTP_AUTH_USERNAME }}
          SANDBOX_HTTP_AUTH_PASSWORD: ${{ secrets.SANDBOX_HTTP_AUTH_PASSWORD }}
          SFCC_HOSTNAME: ${{ matrix.sfcc-hostname }}
